name: ChatSebas CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

  # Job test
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # Paso opcional para depurar: Listar paquetes instalados
    - name: List installed packages
      run: npm list

    # Ejecutar las pruebas con Mocha
    - name: Run tests
      run: npm test

  # Job para construir la imagen Docker 
  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    
    - name: Build Docker image
      run: docker build -t sebasu693/chat-una-app:latest .

    
    - name: Push Docker image
      run: docker push sebasu693/chat-una-app:latest

  security_scan:
    runs-on: ubuntu-latest
    needs: docker
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Trivy for image scanning
      run: |
        sudo apt-get update -y
        sudo apt-get install wget -y
        wget https://github.com/aquasecurity/trivy/releases/download/v0.29.2/trivy_0.29.2_Linux-64bit.deb
        sudo dpkg -i trivy_0.29.2_Linux-64bit.deb
    
    - name: Verify Trivy installation
      run: trivy --version
    
    - name: Full vulnerability scan and generate HTML report
      # Escanea todas las vulnerabilidades y genera un reporte completo en HTML
      run: trivy image --format html --output trivy-report.html sebasu693/chat-una-app:latest
    
    - name: Conditional failure on HIGH and CRITICAL vulnerabilities
      # Vuelve a ejecutar solo con HIGH y CRITICAL, y falla si se encuentran
      run: trivy image --severity HIGH,CRITICAL --exit-code 1 sebasu693/chat-una-app:latest
    
    - name: Upload Trivy HTML report
      uses: actions/upload-artifact@v3
      with:
        name: Trivy HTML Report
        path: trivy-report.html
  
  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "Labciberseguridad"  
        images: "sebasu693/chat-una-app:latest"
